# Generated by Django 5.2.8 on 2025-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
